Switch attribute name from PEP658 'data-dist-info-metadata' to PEP714 'data-core-metadata'
brettcannon/mousebender pull request #104
Opened 2023-08-13 19:53 UTC by derek-keeler

2023-08-13 19:54 UTC, derek-keeler commented
Please ensure my decision to `raise ValueError(...)` was correct. I took `MUST` as such.

2023-08-13 20:54 UTC, brettcannon requested changes
Thanks for working on this! I think there are some test cases to cover and a missing update to one of the `TypedDict`s.

2023-08-13 20:54 UTC, brettcannon commented on mousebender/simple.py
> +                )
```suggestion
                raise ValueError(
                    "'data-dist-info-metadata' differs from 'data-core-metadata'",
                )
```

We should probably raise a new `InvalidDistroMetadata` exception.

2023-08-13 20:54 UTC, brettcannon commented on mousebender/simple.py
Missing updates to the the appropriate `TypedDict`.

2023-08-13 20:54 UTC, brettcannon commented on tests/test_simple.py
> +    # PEP-714 replaces attribute named 'data-dist-info-metadata' with data-core-metadata
```suggestion
    # PEP 714 replaces data-dist-info-metadata with data-core-metadata
```

2023-08-13 20:54 UTC, brettcannon commented on tests/test_simple.py
> +    # while still allowing for it's presence. The original named attribute being present
```suggestion
    # while still allowing for its presence. The original named attribute being present
```

2023-08-13 20:54 UTC, brettcannon commented on tests/test_simple.py
> +    # PEP-714 replaces attribute named 'data-dist-info-metadata' with data-core-metadata
```suggestion
    # PEP 714 replaces data-dist-info-metadata with data-core-metadata
```

2023-08-13 20:54 UTC, brettcannon commented on tests/test_simple.py
> +    # while still allowing for it's presence. The original named attribute being present
```suggestion
    # while still allowing for its presence. The original named attribute being present
```

2023-08-13 20:54 UTC, brettcannon commented on tests/test_simple.py
Should add a test for when `data-dist-info-metadata` is just defined in the HTML without a hash, both by itself and when `data-core-metadata` is also set.

2023-08-13 22:44 UTC, brettcannon commented
Also forgot to mention the docs will need updating (adding the PEP to the list of supported PEPs, the new field as necessary, etc.).

2023-08-14 03:49 UTC, derek-keeler commented on tests/test_simple.py
> +    # PEP-714 replaces attribute named 'data-dist-info-metadata' with data-core-metadata
Replaced each instance of this one...

2023-08-14 03:50 UTC, derek-keeler commented on tests/test_simple.py
> +    # while still allowing for it's presence. The original named attribute being present
English better, me.

2023-08-14 04:10 UTC, derek-keeler commented on tests/test_simple.py
Are we concerned about the values being different IF one is `true` and the other is `TRUE`? The attribute _is_ technically set differently and could be argued as such, but in the special case of `True` do we want to accept case insensitive comparisons? (See the last test case in `test_hash_with_both_pep_658_and_pep_714_metadata_attr_names_unmatched_values` for what I'm going on about).

2023-08-14 04:36 UTC, derek-keeler commented on mousebender/simple.py
I think I've got it. Also I believe we are updating the "_meta" version. However, I'm unclear on this:

Do we _remove_ the `dist-info-metadata` from the `_OptionalProjectFileDetails_1_2`, or leave it there (as some clients _MAY_ choose to read it, if it is there and `core-metadata` is not)?

2023-08-14 05:00 UTC, derek-keeler commented on mousebender/simple.py
Ha! Answered my own question.  They are a union, and so removal is not really an option.

2023-08-14 05:06 UTC, derek-keeler commented on mousebender/simple.py
Alright, I'm done thinking about this for a bit. I think I'll need a hand with versioning this properly - do we need an `ACCEPT_JSON_V2` now? Seems like it...?

2023-08-14 21:50 UTC, brettcannon commented on tests/test_simple.py
`TRUE` is not a valid value according to https://peps.python.org/pep-0658/#specification .

2023-08-14 21:51 UTC, brettcannon commented on mousebender/simple.py
The meta version was **not** bumped by PEP 714.

And don't remove the old key as it's still valid if a server returns it (especially for backwards-compatibility).

2023-08-14 21:53 UTC, derek-keeler commented on mousebender/simple.py
That's great, thank you. I felt I was going down a bit of a rabbit hole there. (It _was_ getting past my bedtime haha).

2023-08-14 21:53 UTC, derek-keeler commented on tests/test_simple.py
Beauty, solved.

2023-10-13 02:37 UTC, closed without merging